version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-aspnetcore-runtime
    steps:
      - checkout
      - run : dotnet restore
      - run: dotnet build
      
  test:
    docker:
      - image: microsoft/dotnet:2.1-aspnetcore-runtime
    steps:
      - checkout
      - run: dotnet  test ./StarterKit.UnitTests/StarterKit.UnitTests.csproj
