version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: dotnet test ./StarterKit.UnitTests/StarterKit.UnitTests.csproj
      - run: docker build -t starterkit ./starterkit.web